version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGROS_PASSWORD=password
      - POSTGRES_DB=url_shortener_db
    ports:
      - "5432:5432"
    # FIX: The healthcheck block is now correctly indented inside the 'db' service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d url_shortener_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    build: .
    command: celery -A app.worker.celery_app worker -P gevent --loglevel=info
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    depends_on:
      db: 
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres_data: