version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=url_shortener_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A app.worker.celery_app worker -P gevent --loglevel=info
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data: